### PR TITLE
Avoid errors when a flag image is missing

### LINKED ISSUE #677: Failure to display peers of a torrent
## Summary

On some torrents peers tab fails to display. I guess it is somehow connected to some specific peer that breaks things. I tested with a torrent and sometimes peers display fine, but sometimes they fail to open.

## Expected Behavior

When you open a torrent and click on peers tab - a list of peers should display.

## Current Behavior

Sometimes (not everytime, because you cannot reproduce it everytime) peers tab fails to display. When it happens if you click on peers tab you cannot see peers tab, but instead you stay on the same tab. 

Example screenshot:

screenshot_2018-06-15_21-54-48

When this happens in Chrome Developer tools you see the below errors:

```
.png$:206 Uncaught Error: Cannot find module './je.png'.
    at a (.png$:206)
    at r (.png$:201)
    at TorrentPeers.js:41
    at Array.map (<anonymous>)
    at t.value (TorrentPeers.js:32)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at d._renderValidatedComponent (ReactCompositeComponent.js:819)
    at d.performInitialMount (ReactCompositeComponent.js:359)
    at d.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
ReactReconciler.js:60 Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:60)
    at d.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at Object.updateChildren (ReactChildReconciler.js:111)
    at m._reconcilerUpdateChildren (ReactMultiChild.js:209)
    at m._updateChildren (ReactMultiChild.js:308)
    at m.updateChildren (ReactMultiChild.js:295)
    at m._updateDOMChildren (ReactDOMComponent.js:944)
    at m.updateComponent (ReactDOMComponent.js:758)
    at m.receiveComponent (ReactDOMComponent.js:720)
ReactReconciler.js:60 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:60)
    at d.getHostNode (ReactCompositeComponent.js:381)
    at Object.getHostNode (ReactReconciler.js:60)
    at Object.updateChildren (ReactChildReconciler.js:111)
    at m._reconcilerUpdateChildren (ReactMultiChild.js:209)
    at m._updateChildren (ReactMultiChild.js:308)
    at m.updateChildren (ReactMultiChild.js:295)
    at m._updateDOMChildren (ReactDOMComponent.js:944)
    at m.updateComponent (ReactDOMComponent.js:758)
    at m.receiveComponent (ReactDOMComponent.js:720)
```

This errors keep repeating over and over...

## Possible Solution

Do not know.

## Steps to Reproduce (for bugs)
1. Click on a torrent.
2. Start to change detail tabs.
3. Click to peer tab.
4. It does not display.
5. Open chrome developer tools and see errors in console.

## Context

Peers tab is a nice functionality and it should work every time.

## Your Environment

* Version used:
  + v1.0.0
  + commit 1493f8f9cbf6d6c94f1083a53aaba82d95d508af 
* Chromium 67.0.3396.87, NodeJS v10.4.1
* Server (Debian Stretch 9.4 x64), Client (Fully updated Arch Linux x64)

### PR DESCRIPTION
**Pull request by stephdewit**
## Description
Display the country code instead of the picture when country flag is missing.

## Related Issue
Fix #677.

## Motivation and Context
See issue.

## How Has This Been Tested?
Run with Node 8.11.2 on Ubuntu 17.10, tested with Safari 12.0 (13606.2.11) and Chrome 69.0.3497.100 on macOS 10.13.6.

## Screenshots (if appropriate):
capture d ecran 2018-09-22 a 19 11 19

(I deleted the 'fr.png' file to test my fix)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: client/src/javascript/components/modals/torrent-details-modal/TorrentPeers.js [hunk 1]
```diff
@@ -16,12 +16,14 @@ export default class TorrentPeers extends React.Component {
     };
   }
 
+  flagImageAsErrored(countryCode) {
+    let {erroredCountryImages} = this.state;
+    erroredCountryImages.push(countryCode);
+    this.setState({erroredCountryImages});
```
Comment (jfurrow) [inline client/src/javascript/components/modals/torrent-details-modal/TorrentPeers.js]: Let's rewrite this without mutating state:
```jsx
this.setState(state => {
  return {erroredCountryImages: state.erroredCountryImages.concat(countryCode)};
});
```

Comment (jfurrow) [reply client/src/javascript/components/modals/torrent-details-modal/TorrentPeers.js]: Ahh just saw that this was copy/pasted from a former block. Will merge as-is.

**Comment by jfurrow** [comment]
Thanks @stephdewit
